all done
AndreiNovikov1984/java-shareit pull request #3
Opened 2023-01-02 12:17 UTC by AndreiNovikov1984

2023-01-03 07:58 UTC, andrew-larkin requested changes
Привет! Выглядит все неплохо, но сборка проекта не проходит, тесты, соответственно, тоже. Надо с этим что-то сделать.

2023-01-03 07:58 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return new ResponseEntity<>(userdto, HttpStatus.OK);
коммент для строки 43 - вместо ? можно использовать класс Void

2023-01-03 08:16 UTC, AndreiNovikov1984 commented
> Привет! Выглядит все неплохо, но сборка проекта не проходит, тесты, соответственно, тоже. Надо с этим что-то сделать.

Привет. Странно, но у меня вчера было отмечено, что "All checks have passed"

2023-01-04 21:02 UTC, andrew-larkin requested changes
Привет! Вообще странно, что у тебя оно запускается, потому что тут жесткий конфликт версий ломбока и mapStruct. Но код, в целом, рабочий, реализация на хорошем уровне. Небольшой рефакторинг (убедись, что во всех контроллерах не создаются доп.переменные) и работа будет принята.

2023-01-04 21:02 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Collection<ItemDto> items = itemService.getItems(userId, from, size);
тут можно не создавать дополнительную переменную с коллекцией, можно сразу возвращать результат: ResponseEntity.ok().body(itemService.getItems(userId, from, size));

2023-01-04 21:02 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        Collection<ItemRequestAnswerDto> itemRequestDtoUpd = itemRequestService.getRequests(userId);
здесь тоже лучше не создавать доп.переменные

2023-01-04 21:02 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<HttpStatus> deleteUser(@PathVariable long id) {
лучше просто Void возвращать

2023-01-05 10:34 UTC, AndreiNovikov1984 commented
> Привет! Вообще странно, что у тебя оно запускается, потому что тут жесткий конфликт версий ломбока и mapStruct. Но код, в целом, рабочий, реализация на хорошем уровне. Небольшой рефакторинг (убедись, что во всех контроллерах не создаются доп.переменные) и работа будет принята.

Привет. Очень странно, не должно быть конфликта ломбока с мапСтрактом - когда я только подключал мапСтракт как раз занимался решением этого конфликта. С тех пор проблем не было.

2023-01-06 14:41 UTC, merged