first working version
AndreiNovikov1984/java-shareit pull request #4
Opened 2023-01-15 11:54 UTC by AndreiNovikov1984

2023-01-16 16:14 UTC, andrew-larkin requested changes
Привет! Отличная работа, остается выполнить небольшой рефакторинг и приложение будет полностью готово.

2023-01-16 16:14 UTC, andrew-larkin commented on getaway/Dockerfile
> +#RUN echo "Europe/Moscow" > /etc/timezone
весь закомментированный код нужно удалить

2023-01-16 16:14 UTC, andrew-larkin commented on getaway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
закомментированный код стоит удалить во всех файлах

2023-01-16 16:14 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                   @PathVariable long bookingId) {
в параметрах лучше передавать врапперы для примитивов (int -> Integer), т.к. нам могут понадобиться свойства класса Object при работе с ними. Это стоит везде поправить

2023-01-16 16:14 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/support/Exept.java
> +public class Exept {
лучше переназвать класс типа ExceptionHandler

2023-01-16 16:14 UTC, andrew-larkin commented on server/src/main/resources/schema.sql
> +
в соседнем data.sql тоже закомментированные строки стоит убрать

2023-01-17 07:54 UTC, AndreiNovikov1984 commented on getaway/Dockerfile
> +#RUN echo "Europe/Moscow" > /etc/timezone
Убрал, но этот код мне нужен для запуска на локальном компьютере, т.к. тесты падают из-за несоответствия времени...

2023-01-18 16:52 UTC, merged